services:
  - type: web
    name: bookora-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=ep-blue-salad-aogmazn6-pooler.c-2.ap-southeast-1.aws.neon.tech; Database=neondb; Username=neondb_owner; Password=npg_u5tCTnvz3SLh; SSL Mode=VerifyFull; Channel Binding=Require;
      - key: Jwt__Key
        value: THIS_IS_A_SUPER_SECRET_KEY_FOR_BOOKORA_2026
      - key: Jwt__Issuer
        value: BookoraAPI
      - key: Jwt__Audience
        value: BookoraClient
